### ISSUE TITLE
Teste 23

### ISSUE THREAD

**Issue by GabCostaSilva** [MarioDeAraujoCarvalho/mini-programming-course-hybrid-with-pwa-with-vuejs-ufms-2018-2#2]
This is a test

**Comment by froeder** [comment]
really?

**Comment by MarioCarvalhoBr** [comment]
Not, This Is Not A Test.
Music: This Is Not A Test
Link: https://www.youtube.com/watch?v=fIrrHUaXpAE
Lyrics:
This Is Not A Test
Fell out of the sky
Hit the ground running
The future is tonight
They'll never see us coming
Takin' by this urgency, won't let this moment pass
The Kingdom is alive
We're stepping on the gas

We're checking in, so check it out
We're dropping in, there ain't no stopping us now
We've only got one shot
Gonna take it now
Goin' all in, gonna make it count
Won't look back, gotta set my eyes
Cause there ain't no practice runs in life

This is not a, this is not a test
This is the real thing
This is not a, this is not a test
This is the real thing
We're gonna go til we got nothing left
This is the real thing
This is not a, this is not a test

We're checking in, so check it out
We're dropping in, there ain't no stopping us now
We're breathing in, we're breathing out
We're dropping in, there ain't no stopping, stopping
We've only got one shot
Gonna take it now
Going all in, gonna make it count
Won't look back, gotta set my eyes
Cause there ain't no practice runs in life

This is life, this is life
This is life, this is life
This is life, this is life
This is life, this is life
Life, life, life, life, life
So don't get left behind

This is not a, this is not a test
This is the real thing
This is not a, this is not a test
This is the real thing
We're gonna go til we got nothing left
This is the real thing
This is not a, this is not a test

We gonna move
Live every second, make it count for you
Make it count, make it count
We gonna move
Live every second, make it count for you
Make it count, make it count
This is not a test
We gonna move
Live every second, make it count for you
