### ISSUE TITLE
testing

### ISSUE THREAD

**Issue by froeder** [MarioDeAraujoCarvalho/mini-programming-course-hybrid-with-pwa-with-vuejs-ufms-2018-2#3]
null

**Comment by MarioCarvalhoBr** [comment]
Em programação de computadores, null é um valor especial para um ponteiro (ou qualquer outro tipo de referência) que indica que este ponteiro, intencionalmente, não se refere a um objeto (ponteiro nulo). Freqüentemente, nos programas escritos na linguagem C, um valor binário 0 (zero) é utilizado como valor nulo, já que a maioria dos sistemas operacionais consideram um erro acessar um endereço de memória "tão baixo".
Fonte: https://pt.wikipedia.org/wiki/Null_(programa%C3%A7%C3%A3o)
